% =========================================================================
% BLSimulation project
% =========================================================================
% Description
%    Performs a high-fidelity enthalpy balance audit across vertical slices
%    of the 2D computational domain in boundary layer flow. Computes local energy
%    conservation residuals (E_in + Q_wall - E_out - E_top = 0) in Watts [W]
%    to validate numerical consistency across forced and natural convection solutions.
%
% Syntax
%    [x_coords, de_error] = energy_conservation_profile(Fields, Param)
%
% Input arguments
%    Fields   : Structure containing 2D computational grid and physical fields
%               (.X, .Y, .U, .V, .T, .q_wall) generated by calculate_physical_fields.
%    Param    : Execution configuration and simulation parameter structure.
%
% Output
%    x_coords : Vector of cell-centered midpoint x-coordinates [m].
%    de_error : Local energy conservation residual vector across slices [W].
%
% Example
%    [x_mid, err_energy] = energy_conservation_profile(PhysFields, Param);
%
% Notes
%    - Accounts for Ostrach similarity scaling and upwind entrainment enthalpy.
%    - Supports multiple audit modes: 'EXACT' (analytical reconstructed gradient),
%      'STRETCHED_FINE' (2nd-order non-uniform stencil), and fallback 1st-order schemes.
%    - Numerical Y-integration uses trapezoidal integration over non-uniform node spacings.
%
% See also
%    calculate_physical_fields, trapz
%
% Author      : Rvieytes
% Assisted by : Gemini 3.6; OpenAI ChatGPT
% Date        : 15/06/2026
% Version     : 0.0.1
% =========================================================================
function [x_coords, de_error] = energy_conservation_profile(Fields, Param)

    % --- 1. Data Extraction ---
    X = Fields.X;
    Y = Fields.Y;
    U = Fields.U;
    V = Fields.V;
    T = Fields.T;

    [~, nx] = size(U);
    dx      = X(1, 2) - X(1, 1);

    % Physical properties
    phys   = Param.phys;
    k_cond = phys.k;
    rho    = phys.rho;
    cp     = phys.cp;
    T_inf  = phys.T_inf;
    T_rel  = T - T_inf; % Relative enthalpy reference (T_inf = 0)

    % --- 2. Wall Heat Flux (Energy Source) ---
    switch upper(Param.num.audit_mode)
        case 'EXACT'
            % Analytical wall gradient reconstructed from similarity solution g'(0)
            q_dot_wall = Fields.q_wall * dx;

        case 'STRETCHED_FINE'
            % 2nd-order numerical gradient calculated from non-uniform wall grid
            h1 = Y(2, 1) - Y(1, 1);
            h2 = Y(3, 1) - Y(2, 1);
            c1 = -(2 * h1 + h2) / (h1 * (h1 + h2));
            c2 = (h1 + h2) / (h1 * h2);
            c3 = -h1 / (h2 * (h1 + h2));

            dTdy_num   = c1 * T(1, :) + c2 * T(2, :) + c3 * T(3, :);
            q_dot_wall = -k_cond * dTdy_num * dx;

        otherwise
            % Standard 1st-order finite difference fallback
            dy_0       = Y(2, 1) - Y(1, 1);
            q_dot_wall = -k_cond * (T(2, :) - T(1, :)) / dy_0 * dx;
    end

    % --- 3. Advective Enthalpy Fluxes (Energy Transport) ---

    % A. X-Direction: Internal Enthalpy Flow
    E_dot_x = zeros(1, nx);
    for i = 1:nx
        % Integrate rho * cp * u * T_rel along Y using local grid coordinates
        E_dot_x(i) = rho * cp * trapz(Y(:, i), U(:, i) .* T_rel(:, i));
    end

    % B. Y-Direction: Top Boundary Flow (Upwind Logic)
    V_top = V(end, :);
    T_top = T_rel(end, :);

    % Upwind: If V_top < 0 (entering), fluid brings ambient enthalpy (T_rel = 0).
    % If V_top > 0 (leaving), fluid carries local boundary layer enthalpy.
    E_dot_top = (rho * cp * V_top .* (V_top > 0) .* T_top) * dx;

    % --- 4. Global Balance Calculation ---
    % Conservation law on vertical slice: [E_in + Q_wall] = [E_out + E_top_out] + Residual
    E_in  = E_dot_x(1:end-1);
    E_out = E_dot_x(2:end);

    % Mid-point averaging for flux consistency over spatial step dx
    q_wall_avg = 0.5 * (q_dot_wall(1:end-1) + q_dot_wall(2:end));
    E_top_avg  = 0.5 * (E_dot_top(1:end-1) + E_dot_top(2:end));

    % Final Residual in Watts [W]
    de_error = (E_in + q_wall_avg) - (E_out + E_top_avg);

    % Cell-centered X coordinates for plotting and diagnostic evaluation
    x_coords = 0.5 * (X(1, 1:end-1) + X(1, 2:end));

end
